### ISSUE TITLE
The select drop-down in public groups poorly interacts with "Open in new tab"

### ISSUE THREAD

**Issue by jakub-** [loomio/loomio#1885] opened 2015-02-09 22:25 UTC
Steps:
1. Go to https://www.loomio.org/explore.
2. Choose a category from the drop down.
3. Try to open a category in a new tab.
4. ?

Arguably, it's a very desktop-specific annoyance but I think "Open in new tab" is one of those things that Web sites should still be friendly towards.

**Comment by robguthrie** [comment] 2015-02-09 23:15
We consider explore a bit of a hit and a miss. It's actually really broken
in a lot of ways, this is relatively minor compared.

We have a new concept of 'networks' coming really soon, and we're focusing
on that rather than fixing this.

**Comment by gdpelican** [comment] 2015-02-10 10:44
I think this is a 'wontfix', we'll look to get functionality we were looking for in the Explore page in a better way in 1.0 :lollipop:

**Closed by gdpelican** 2015-02-10 10:44 UTC
Labels: Bug, Rewritten in 1.0

**Comment by robguthrie** [comment] 2015-02-10 19:10
I hate 'Wonfix'. Just because it feels more annoying than helpful as a label. 

I think in this case, this isn't really about a bug, it's about a poor design, and it highlights that there is quite a lot of design work needing to go into enthusiastically and fairly displaying public content. Which was the intention behind the explore page.

I'd rather label this "Needs major redesign" than wontfix, as it's more representative of the problem.

I've been thinking that a challenge we have as an open source project is learning how to discuss UI/UX design on the internet - but not getting much further than that.

**Comment by denjello** [comment] 2015-02-10 19:14
I agree with you @robguthrie. For me seeing wontfix in this context is more like "broken until 1.0" which in a deployed system is not exactly cool. Granted, this is "pretty" trivial, but the problem is still around. I mean really - the fix is just a couple lines of coffeescript with the right selector and a bootstrap wrapper, no?

**Comment by robguthrie** [comment] 2015-02-10 19:31
Well.. it might be, but it's not certain - I could imagine it taking up 4 hours or maybe a bit more to get this really production ready.. even then we don't know how good the fix will be, and the explore experience isn't going to be significantly better at the end of it IMO.

Really happy to see suggestions/patches but not happy to experiment on patches myself/'as part of the core team' given my current workload and priorities.

**Comment by gdpelican** [comment] 2015-02-10 19:36
I'd venture that it is wontfix [maybe a better term is 'low priority'?], because we don't have capacity to fix it, or of even supporting an open source contributor to work on it. (And have stated so many times before in relation to the explore page; so many more exciting and useful things to be focused on!)

As Rob says, even a 'simple fix' like this one is / could be a decent chunk of developer time that is likely better spent elsewhere.

**Comment by rdbartlett** [comment] 2015-02-10 20:22
Relevant: a user just created a Loomio tutorial (in Spanish) to encourage
people to join and participate in their Loomio group, and their starting
point is "go to the Explore page and find our public group".

So people are using it, even if me and Rob think is broken and dumb.

https://www.youtube.com/watch?v=KfBFkJAa9jA&feature=youtu.be


On 11 February 2015 at 08:36, James Kiesel <notifications@github.com> wrote:

> I'd venture that it is wontfix [maybe a better term is 'low priority'?],
> because we don't have capacity to fix it, or of even supporting an open
> source contributor to work on it. (And have stated so many times before in
> relation to the explore page; so many more exciting and useful things to be
> focused on!)
>
> As Rob says, even a 'simple fix' like this one is / could be a decent
> chunk of developer time that is likely better spent elsewhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/issues/1885#issuecomment-73767662>.
>



-- 

Richard D. Bartlett
Loomio co-founder
rich@loomio.org

<http://loomio.org/>
