### ISSUE TITLE
parent group and subgroups shown on the group page

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3135] opened 2016-03-21 22:36 UTC
it seems to fluctuate between showing me all the subgroups or just the ones I'm a member of. I think that the latest should be the right one to be shown to me on my groups page for easy access... ? any way, here are the screen shots: 

![parent and subgroup](https://cloud.githubusercontent.com/assets/15793070/13936403/59d8ccb6-f022-11e5-90c8-881205911e32.png)
![parent and subgroup1](https://cloud.githubusercontent.com/assets/15793070/13936402/59d59082-f022-11e5-8b20-c2bbfb5d928e.png)

**Comment by gdpelican** [comment] 2016-03-22 20:59
Yep, we know about this, a duplicate of #3009 

I've reproed it, but don't have a fix yet. Silver lining is we're never showing subgroups that shouldn't be visible.

**Closed by gdpelican** 2016-03-22 20:59 UTC
