### ISSUE TITLE
Last coordinator can't deactivate group - admin panel says group is deactivated

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#2757] opened 2015-11-26 20:34 UTC

**Comment by gdpelican** [comment] 2015-12-02 00:45
Going to need some more details on this one, as I'm unable to reproduce and am not quite sure what this is saying. If it's deactivated in the admin panel, it's deactivated in the DB, which means they shouldn't be getting to the group page at all.

**Comment by gdpelican** [comment] 2015-12-02 07:05
Closing for now, feel free to reopen if we can find a repro.

**Closed by gdpelican** 2015-12-02 07:05 UTC
