### ISSUE TITLE
My picture does not appear, instead a long hash appears over the placeholder

### ISSUE THREAD

**Issue by asdofindia** [loomio/loomio#1927] opened 2015-02-19 01:18 UTC
I'm not particularly sure what I did to achieve this. But I've probably removed the gravatar or set a picture myself or something. I'll attach 3 images to make this clear.

Here's my settings page
![screenshot from 2015-02-19 06 46 36](https://cloud.githubusercontent.com/assets/945777/6260325/26507c66-b803-11e4-8e4c-ab2db5026063.png)
Here's how the top bar looks like 
![screenshot from 2015-02-19 06 42 16](https://cloud.githubusercontent.com/assets/945777/6260332/37824604-b803-11e4-9bc3-d670847dd220.png)
Here's how commenting looks like
![screenshot from 2015-02-19 06 42 21](https://cloud.githubusercontent.com/assets/945777/6260334/434b01f6-b803-11e4-863e-b397bf8e0378.png)

**Comment by gdpelican** [comment] 2015-02-19 02:02
Hm, thanks for bringing this up @asdofindia. I'll have a poke at some point soon and see if I can't reproduce. If you come across any more details, do let us know?

**Comment by denjello** [comment] 2015-02-19 11:27
What is happening is that the alt is being rendered into the image block because your connectivity to gravatar / AWS is slow / nonexistent.

The following is the html that is being rendered (from loomio.org):
```
<img alt="015f491a6dea80e087aa0685e12b12f5" src="https://secure.gravatar.com/avatar/015f491a6dea80e087aa0685e12b12f5.png?d=none&amp;r=pg&amp;s=35">
```

I stumbled across this while fixing the double avatar issue. <https://github.com/loomio/loomio/issues/1850>. Unfortunately the pull-request wasn't accepted in a timely manner because of more pressing issues, and now it conflicts with the master branch in dozens of ways. As I don't have the time or energy to do the pull-request again, I thought I would at least share my research on this matter for you:

The main issue is that an alt is not being declared in `app/views/base/_avatar.html.haml:16`
```
     = image_tag user.avatar_url(size)
```
When an image is not loadable, *most* browsers show the alt text in that bit of dom where the image is located.

This edge case was solved by creating an alt text. (the size,kind) variables relate to the fact that the algorithm for calling the avatar type (in `app/models/user.rb`)was not being correctly instantiated:
```
      = image_tag user.avatar_url(size,kind), alt: kind
```
After thinking about it some more, it might make more sense to use 
```
      = image_tag user.avatar_url(size,kind), alt: user.avatar_initials
```
because then at least the text visible while loading is at short enough not to spill out of the div && it is relevant to the user.

This might not the best solution, but this way on slow connections that flash of unstyled content doesn't happen. Another solution might be to simply modify the `.avatar-canvas` css class in `app/assets/stylesheets/unstructured/_users.scss94`. Probably both should be done.

```
  &.gravatar-user-avatar, &.uploaded-user-avatar {
    border:  1px solid rgba(255, 255, 255, 0);
    width:inherit;
    overflow:hidden;
  }
```

**Comment by HSalmon** [comment] 2015-03-19 21:56
Had further confirmation of this bug this morning:

![](https://uploads.intercomcdn.com/i/o/893539/cbff9dc0e8772356716f4880/loomio%2520pictures%2520bug.png)

**Comment by Flaburgan** [comment] 2015-03-24 08:35
Hi, Fla from the diaspora* team.

I can confirm that the alt is displayed when Gravatar is blocked (by Ghostery or RequestPolicy for example). Then, the hash comes over the content. A quick solution is
```
img {
  display: inline-block;
  overflow: hidden;
}
```

I tested this with Firefox and it works. I would gladly open a PR if someone points me where the css code is (I searched in ```assets/stylesheet``` but I never contributed to loomio so not sure about where the code exactly is).

**Comment by gdpelican** [comment] 2015-03-24 08:53
Thanks @Flaburgan!

Hm.. I guess I'd be not 100% convinced that we're able to change all images everywhere to `display: inline-block` without breaking something, so might require a careful QA. Does it not work to just set the overflow to hidden?

In any case, a wide-swingin' css style like that probably wants to live in `app/stylesheets/unstructured/_main.scss`

PS Go Diaspora :star:!

**Comment by Flaburgan** [comment] 2015-03-24 09:01
I of course meant ```body.discussions.show img``` I didn't check exactly what should be put here, I didn't want to put that on every images, just avatars.

**Comment by robguthrie** [comment] 2015-03-24 20:17
Thanks for the tip Fla!

**Comment by robguthrie** [comment] 2015-11-17 19:46
closing as it's a beta issue we're not seeing in angular

**Closed by robguthrie** 2015-11-17 19:46 UTC
Labels: Bug, Weird
