### ISSUE TITLE
Bug when creating a new tag from the group page

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9085] opened 2022-10-24 11:23 UTC
When creating a tag from the "Category tags" menu in the group page the tag is created but shows in the list only after refreshing.

Steps to reproduce:

1 - go to Category tags in a group

![Screen Shot 2022-10-24 at 13 15 14](https://user-images.githubusercontent.com/333447/197514218-7a7b20d0-2583-491e-8f17-e3bc24b70977.png)

2 - When clicking in the "New tag" button the following error appears in the console:

`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`  @ | index.js:123

After refreshing the page the created tag is there, so this is not a blocker.

**Comment by robguthrie** [comment] 2022-11-17 03:56
Hi @anarute - I can't reproduce this problem. Creating tags works fine and they show up immediately during my testing.

Feel free to reopen if necessary.

**Comment by anarute** [comment] 2022-11-17 12:07
This is still happening in all of our instances and I just tried locally using the master branch without any custom modification:

https://user-images.githubusercontent.com/333447/202441659-a63dfe3c-1100-456e-bc95-c9612dec4b36.mov

In this video you can also see the reordering issue I reported in https://github.com/loomio/loomio/issues/8448#issuecomment-1318530158

**Comment by robguthrie** [comment] 2022-11-23 03:59
Thanks for the video. That's what I needed :) The problem was not happening for me, because I was opening the category tags modal via the edit discussion form. 

This is now fixed in master. Thanks again for you help.

**Comment by robguthrie** [comment] 2022-11-23 03:59
I've also fixed the issue where you need to reload after creating a new tag. They will show up instantly now.

**Closed by robguthrie** 2022-11-23 03:59 UTC
