### ISSUE TITLE
yesterday on loomio email is not getting inline styles

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3377] opened 2016-05-19 20:10 UTC
I would love to pair with someone on this because I've tried a few times to fix and have not sorted it.
![image](https://cloud.githubusercontent.com/assets/486367/15408042/52399c60-1e62-11e6-9cc3-b6b829c2054f.png)

**Comment by gdpelican** [comment] 2016-05-23 13:18
Dupe of #3319

**Closed by gdpelican** 2016-05-23 13:18 UTC
