### ISSUE TITLE
Proposal closing soon notification delivered despite group being muted

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2712] opened 2015-11-16 21:12 UTC
Just had a report from Malcolm that he has muted the Loomio Community, but is still sporadically getting messages. The latest one was the `Closing in 24 hours: Do You want to invite people by mail sent by Loomio?` notification.

**Comment by gdpelican** [comment] 2015-11-17 06:06
Our thread level notifications override the group level notifications, so I reckon he has a particular thread marked as 'normal'; motion closing soon is an important event, so everyone with notification level over 'quiet' will get an email.

I think the solution for this is to update all of the thread volumes in a group to nil when it is set as mute, which will effectively mute all threads unless one gets overridden at a later date.

**Comment by gdpelican** [comment] 2015-11-17 06:09
Going to close this as a dupe of #2708, since it's the same issue.

**Closed by gdpelican** 2015-11-17 06:09 UTC
Labels: Bug

**Comment by robguthrie** [comment] 2015-11-17 07:17
it's not a dupe of Alanna's bug. but that's ok. Having an "apply this
volume to all threads" (which acutally changed group volume and nulled
thread volume) would fix this.

**Comment by gdpelican** [comment] 2015-11-17 07:30
I reckon it's not a bug at all, just something we need to explain better,
and yeah, feature request for more intuitive volume updating.

**Comment by rdbartlett** [comment] 2015-11-17 07:32
Ah yeah, it's not a bug. I started that thread in Contributors, which meant
the thread volume would have been Normal for him. Then I shifted it into
Community, which Malcolm has muted, but he still got this notification
email because the thread volume didn't change when I moved it. Edge case.
