### ISSUE TITLE
Comment box jumps down to bottom of screen

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#4743] opened 2018-07-05 07:12 UTC
I scroll so the text box is in the middle of the screen, but every time I type, it jumps down to the very bottom of my screen. Seems there's no way to type except along the bottom edge.

![ezgif-4-9277bdc650](https://user-images.githubusercontent.com/5498878/42307642-3f0907d2-8087-11e8-947a-cb01934289c0.gif)

I'm using Firefox on Mac.

**Comment by robguthrie** [comment] 2018-07-05 08:50
Ok I've come up with something that should fix the worst of the problem.

The issue is caused by angular-material which manages the textarea you're typing into. It has an autoresize feature so the box grows as you type. When it resizes it forces the scroll and focus to the bottom of the screen, which is what people don't like.

I've added max-rows of 5, so after 5 rows it will stop growing, but you can still manually resize the text area to the size you would like. 

Keen to learn if that helps. Deploying now.

**Comment by alannallama** [comment] 2018-07-05 23:44
I looked for related issues but I must have missed the other ones. Sorry!
It's now jumping less. Thanks for the quick improvement! But it's still jumping.

Screenshot: https://i.gyazo.com/67c03df1f3e01ff2b756a09cccf3bc70.mp4

**Comment by robguthrie** [comment] 2019-10-10 20:12
fixed in loomio 2.0

**Closed by robguthrie** 2019-10-10 20:12 UTC
