### ISSUE TITLE
Getting two Proposal closing in 24 hours emails per proposal

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3503] opened 2016-07-14 07:08 UTC
![image](https://cloud.githubusercontent.com/assets/1380991/16830965/4b5c0396-49f6-11e6-8c4e-0ad0369fa922.png)

**Comment by mhjb** [comment] 2016-07-14 07:09
two Slack notifications too

**Comment by gdpelican** [comment] 2016-07-15 05:09
Yeah, that was weird, eh? This was a bug before, and it seems to have cooled off a lot, but seems like there's still an edge case here somewhere.

**Comment by gdpelican** [comment] 2016-07-18 07:32
@mhjb Do you know if that proposal was extended from its original date or not?

**Comment by mhjb** [comment] 2016-07-18 07:39
It was

**Comment by gdpelican** [comment] 2016-08-30 18:14
I made a dupe of this issue #3652 , then fixed the bug. Now I'm closing this. 🌈

**Closed by gdpelican** 2016-08-30 18:14 UTC
Labels: Bug, Priority: Low, Weird
