### ISSUE TITLE
Writing in loomio

### ISSUE THREAD

**Issue by ckiltolier** [loomio/loomio#4442] opened 2017-11-29 02:14 UTC
**When does the issue happen** : Whenever I write something longer than 10 lines in loomio

**What happen** : The text become grey and under a double down arrow

![writing in loomio bug](https://user-images.githubusercontent.com/11541071/33354345-cd15845c-d488-11e7-89f0-b9cb28ec2c3b.png)

I can't select anything in this lane. It's very annoying as I can't modify anything without struggling.

Thank you !

**Comment by juliencarnot** [comment] 2018-02-20 12:06
Do you still reproduce this issue? Recent updates might solve it: I had the two arrows but scrolling down the modal (not the text area) I could edit the last lines...

I think the writing experience could be much better if the modal was 720px wide instead of 480px and if the textarea height would expand with its content, leaving only one scrollbar at the modal level.

**Comment by alexgleason** [comment] 2018-03-08 19:27
This is a really complex UI problem that I'm not sure how to solve. I understand why you did it, but it's not working very well on desktop where you have a lot of content to write out and intend to edit it directly in the text field.

So, there's two boxes with scroll bars, the text field itself and the parent container. If the user types enough text into the text field that it would overflow on the Y axis, you want the cursor to follow it so it appears on the screen. This is what Loomio tries to do, and theoretically it makes sense.

But I'm having two issues with it right now:

First, when the text reaches the last line, that whole line gets blocked by the faded arrow thing. I think it should allow for some space.

Here's what happens when the cursor is on the last line. You can't see it, but my cursor is right at the end of `**Envelope**`:

![screenshot from 2018-03-08 14 16 31](https://user-images.githubusercontent.com/3639540/37171303-6ce2753a-22db-11e8-8271-28413ac11735.png)

What I actually want is something closer to this:

![screenshot from 2018-03-08 14 17 01](https://user-images.githubusercontent.com/3639540/37171372-a3d4a04a-22db-11e8-9676-539cdab62430.png)

Solving this problem would go a long way to improving this UI, and I think it should be a relatively simple solution; just add like 30px or so to the scroll calculation so the line I'm typing on appears above the arrow bar.

The second issue is more complicated and might require rethinking the whole behavior of the box.

If I move my cursor to a previous location and type, the parent container scrolls up to the point where my cursor would be the last line of the the screen. This adds to the frustration of the above issue because I'm trying to work around it by adding blank lines to the end and bringing my cursor back up, but when I type it forces the text behind the arrow bar again.

When you're typing and the text is going down the page, you want the box to scroll with you. When you return to a previous location and edit, you don't want the scrollbar to force that point down to the bottom. Maybe we can detect whether the user is typing new lines or editing previous lines; like by checking the text buffer and seeing if characters are changing at the end versus changing in the middle. If the scroll happens only when text is appended to the end I think that would be bueno.

**Comment by juliencarnot** [comment] 2018-03-09 21:40
Thanks for the input on this!

The more I think about it, the more the scroll indicator feels superfluous, once there's **one** scrollbar on the side. It is a convenient and well known scroll indicator, that doesn't get in your way when typing.

I also realized that some (silent) users in my groups missed the context textarea, which is styled as a text input field by angularjs material. It looks very sleek and is maybe expected by android mobile users, but it makes for an obscure UI for some and does not incite users to discuss and participate...

Here's a new screenshot of this PR:
![image](https://user-images.githubusercontent.com/3848493/37231054-fbf9e302-23e9-11e8-83e1-b98bd00a3a56.png)

The modal still scrolls/bounce so that where you start typing within a long text is shown at the very bottom, which I find very distracting and useless (it's not how the [angular material demo works](https://material.angularjs.org/latest/demo/input)), but I can't figure out what does it...

**Comment by gdpelican** [comment] 2018-05-07 05:47
I'm going to close this as a dup of https://github.com/loomio/loomio/issues/4367; this is getting closer to the top of the list now that announcements is out.

**Closed by gdpelican** 2018-05-07 05:47 UTC

**Comment by juliencarnot** [comment] 2018-05-07 06:00
OK, what do you think about [PR 4548](https://github.com/loomio/loomio/pull/4548) before the WYSIWYM feature?
