### ISSUE TITLE
Drafts do not work on editing 

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2807] opened 2015-12-13 22:40 UTC

**Comment by gdpelican** [comment] 2015-12-13 23:29
Uh, on editing what? I'd really appreciate a little more detail in these 'bug reports' @rdbartlett

**Comment by rdbartlett** [comment] 2015-12-14 00:36
Sorry for the brevity, was throwing notes down in a meeting. I saw this not
working on editing comments, but Rob believes it is the same for editing
anything.

**Comment by gdpelican** [comment] 2015-12-16 05:18
This is actually intended behaviour at the moment... I found it really annoying to open up an edit modal, change a bunch of things, and then go back only to find them still there.... I kinda expected it to be a 'reset' to close the modal.

So I think this needs a little design, and a 'discard draft' button somewhere... it can't be as silent as the create draft stuff, because when you go to edit something, I think you expect it to start off the way it is.

**Comment by robguthrie** [comment] 2015-12-16 05:23
Hrrmm.. I see your point. In that case I think we need to put the confirm
cancel back in there.

**Comment by gdpelican** [comment] 2015-12-16 05:29
Yarr, totally agree.

**Comment by gdpelican** [comment] 2015-12-18 14:13
Closing for now, I'll put a card on the roadmap for confirm cancel.

**Closed by gdpelican** 2015-12-18 14:13 UTC
