### ISSUE TITLE
Join group flow is seriously but not terminally broken.

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4552] opened 2018-02-21 05:34 UTC
I (my normal account) sent Rich Testy (my test account) an invitation link so they could join my Demo Group (closed group, default settings). 

Testy follows the link, is asked to sign in, creates a new account with a new email, and receives the Sign In To Loomio email. Testy follows the link, and arrives on the Demo Group page, but he is not a member, so the group looks empty! (There are 3 threads and another member.) He clicks Ask To Join. 

![image](https://user-images.githubusercontent.com/970124/36464396-798407d4-1734-11e8-8fe4-50e7c62f6998.png)

I'm waiting for his request, so I'm already looking at my group page when I see an in-app notification pop up in a couple seconds (nice!). I click the notification, but nothing appears to happen. I navigate elsewhere, then click the notification again, and the group page reloads with the pending membership (I would have expected the notification to link straight to the membership_requests page).

Testy gets the notification instantly, clicks it, and nothing happens on screen, though the url in the address bar now has "%3Fuse_key=true" appended to it. He reloads the page manually and is finally in the group.

**Comment by robguthrie** [comment] 2018-02-22 01:59
Hi Rich.

I can't reproduce this at all.

I invited "Rob test" to my new group  "test group"
rob test got an "invited to join group" email, and follows the link.
he sees a sign in to continue screen, and confirms his email address, enters his name and is told to check his email again,
he checks his email again and is now looking at the group page as a member.

The biggest issue here is that I had to check my email twice, which is somehting we can improve.

Can you repeat your test please?

**Comment by juliencarnot** [comment] 2018-03-04 19:36
I reproduce the same process than Rob, which is indeed ackward.

This might also benefit this issue: #4549 Seems like the first e-mail could contain a verification link, and the user could be created before, upon invitation by admin (using email prefix and an increment as username), instead of needing the user to set his username then get the verification e-mail. In this case, pending invited users could receive notifications as as default user would, and could opt-out by deleting their account?

Groups or administrators inviting a lot of people that end-up opting out could be followed by admin to avoid spammers.

**Comment by gdpelican** [comment] 2018-03-05 03:28
I'm closing this in favor of #4566, which will be actionable.

**Closed by gdpelican** 2018-03-05 03:28 UTC
Labels: Bug
