### ISSUE TITLE
markdown in group descriptions not formatted in other contexts

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3467] opened 2016-07-07 00:02 UTC
Formatting in group descriptions isn't coming through when they are displayed in some other contexts. It's showing up in plain markdown text.

On the explore page:
<img width="376" alt="screen shot 2016-07-07 at 12 00 44 pm" src="https://cloud.githubusercontent.com/assets/5498878/16638329/7d346d0c-443a-11e6-9b1b-ce8e6339bca8.png">

Subgroup listing:
<img width="334" alt="screen shot 2016-07-07 at 12 02 00 pm" src="https://cloud.githubusercontent.com/assets/5498878/16638350/9e8b9304-443a-11e6-86bc-efebdf23034f.png">

**Comment by gdpelican** [comment] 2016-07-07 00:09
This is a duplicate of #3033 

Further context is; it's hard to change markdown to plaintext because markdown is plaintext. Surprised that there's not an industry consensus on what to do about it. Will get to it at some point.

**Closed by gdpelican** 2016-07-07 00:09 UTC
