### ISSUE TITLE
Cannot remove choice in multiple choice poll

### ISSUE THREAD

**Issue by despens** [loomio/loomio#8293] opened 2022-01-11 16:08 UTC
When changing a vote in a multiple choice, checkbox-based vote, I am not able to _remove_ a checked box, only to _add_ more checked checkboxes.

This happens on versoin 2.11.4 [deployed via docker](https://github.com/loomio/loomio-deploy/).

**Comment by robguthrie** [comment] 2022-01-13 01:57
I think this is the intended behaviour for a poll with votes on it (although that might be the wrong behaviour to implement). 
Does this poll have votes placed already?

It might help me understand more clearly if you provide an example screenshot or two? Thank you!

**Comment by despens** [comment] 2022-01-15 12:39
Ah yes I realize this is very easy to misinterpret, Here is a video capture of the process:

https://user-images.githubusercontent.com/571494/149621957-cb282f15-d9a2-4f47-a0d3-3079b8a2a10e.mp4

1. Cast a vote with one checkbox clicked
2. Change the vote, uncheck that checkbox and check another one
3. Now both checkboxes are registered as being picked.

It is impossible to change an accidentally checked checkbox back to unchecked again.

**Comment by robguthrie** [comment] 2022-01-24 03:49
Oh, I'm sorry this has taken a long time to respond to, @despens. I've been on holiday. 

This bug was already fixed in v2.11.5. The latest version is v2.11.11

Sorry I did not understand the issue sooner, I though it was about editing the poll, rather than the voting form.

**Closed** 2022-01-24 03:49 UTC

**Comment by despens** [comment] 2022-01-24 09:58
Thanks @robguthrie, superb! I'm using the "stable" channel of the docker distribution, so will have to wait for that to be updated.

**Comment by robguthrie** [comment] 2022-01-24 22:31
Oh, ok good to know. I should probably setup a Github action so that branch follows the latest release..

**Comment by robguthrie** [comment] 2022-01-25 08:34
@despens the stable branch has been updated just now.
