### ISSUE TITLE
character encoding in comment form helper text

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4279] opened 2017-08-31 14:06 UTC
The group is calleed "Bartlett & Baird family business" but the text says "Bartlett &amp; Baird"

![image](https://user-images.githubusercontent.com/970124/29927306-3bf39116-8e66-11e7-9f85-1c8e3019539d.png)

**Comment by gdpelican** [comment] 2017-08-31 19:59
Er, dupe of https://github.com/loomio/loomio/issues/4277 :) <3

**Closed by gdpelican** 2017-08-31 19:59 UTC
Labels: Bug, Easy Win, Priority: Trivial
