### ISSUE TITLE
"[user] updated the thread title and context" — but I only updated the context

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2763] opened 2015-11-29 22:34 UTC

**Comment by robguthrie** [comment] 2015-12-21 23:32
Not able to reproduce this:
![image](https://cloud.githubusercontent.com/assets/486367/11944094/1360b058-a8a8-11e5-8213-7283157f1799.png)

Closing for now. Thanks Rich

**Closed by robguthrie** 2015-12-21 23:32 UTC
Labels: Bug
