### ISSUE TITLE
Lintel too big for britches

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3935] opened 2016-12-08 12:22 UTC
![image](https://cloud.githubusercontent.com/assets/970124/21009882/598d1086-bd8c-11e6-9d02-ebdcb9fa3383.png)

**Comment by gdpelican** [comment] 2016-12-08 12:26
Dupe of #3931

**Closed by gdpelican** 2016-12-08 12:26 UTC

**Comment by rdbartlett** [comment] 2016-12-08 12:38
Do I get an extra point for poetic language?
