### ISSUE TITLE
Graphical emoji helper does not insert text in post

### ISSUE THREAD

**Issue by jessykate** [loomio/loomio#3721] opened 2016-09-15 22:35 UTC
![screencast](http://g.recordit.co/tJCBR577WW.gif)

mac os x , chrome browser, checked browser console and no JS errors.

**Comment by gdpelican** [comment] 2016-09-16 07:43
Hrm, I can't reproduce this under the same OS / browser. Any other mitigating factors I should be aware of? Does it happen for all groups, all the time?

**Comment by HSalmon** [comment] 2016-10-04 01:54
I experienced this for a short period but it's working for me now

**Comment by mhjb** [comment] 2016-11-17 21:56
Still failing for you, @jessykate ?

**Comment by HSalmon** [comment] 2016-12-09 01:07
I'm wondering if we can close this now, seeing as we haven't had further feedback that this is still an issue?

**Comment by HSalmon** [comment] 2016-12-19 02:11
Closing for now, we can reopen if we get further reports

**Closed by HSalmon** 2016-12-19 02:11 UTC
Labels: Bug, Needs Confirmation
