### ISSUE TITLE
Previous proposals marked as undecided even though I have participated

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2724] opened 2015-11-17 20:15 UTC
I have participated in most of these proposals but they are marked as undecided:

![image](https://cloud.githubusercontent.com/assets/970124/11223451/d43353ce-8dd4-11e5-9ffa-da7852c85c68.png)

**Comment by robguthrie** [comment] 2015-11-17 20:35
I reckon this might be due to the default results limit.

**Comment by robguthrie** [comment] 2015-11-18 04:31
Thanks Rich. This is a dupe of #2696. We'll monitor the fixing process in that issue

**Closed by robguthrie** 2015-11-18 04:31 UTC
