### ISSUE TITLE
triple notifications (and emails) for poll create

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4321] opened 2017-10-01 20:46 UTC
![image](https://user-images.githubusercontent.com/486367/31058803-7efcf8e0-a756-11e7-967d-981d1938bba6.png)

https://www.loomio.org/p/5XVu1lIA

Also got 3 emails for this....

**Comment by gdpelican** [comment] 2017-10-09 18:15
This is a dupe of https://github.com/loomio/loomio/issues/4320. I'll look at it now.

**Closed by gdpelican** 2017-10-09 18:15 UTC
