### ISSUE TITLE
Let's strip out markdown from metadata e.g. Twitter scrapes

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3510] opened 2016-07-15 04:23 UTC
![image](https://cloud.githubusercontent.com/assets/1380991/16863588/6aa01a8c-4aa8-11e6-8385-e4cd53b9bbe4.png)

**Comment by gdpelican** [comment] 2016-07-15 04:51
Dupe of #3033

**Closed by gdpelican** 2016-07-15 04:51 UTC

**Comment by mhjb** [comment] 2016-07-15 04:59
sorry! forgot about that one
