### ISSUE TITLE
Visiting a link from a Loomio email when logged out gives mega-unfriendly message

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3285] opened 2016-04-28 09:56 UTC
![image](https://cloud.githubusercontent.com/assets/1380991/14882303/120a3938-0d8c-11e6-8530-8e6806f0e747.png)

**Comment by gdpelican** [comment] 2016-04-28 10:05
Dupe of #3174

**Closed by gdpelican** 2016-04-28 10:05 UTC

**Comment by mhjb** [comment] 2016-04-28 10:06
sorry JK
