### ISSUE TITLE
thread (that I started) is missing from group page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3468] opened 2016-07-07 08:12 UTC
![image](https://cloud.githubusercontent.com/assets/970124/16646592/ff7ee564-447e-11e6-9ced-4b32b128e735.png)

I'm looking for the Q3 plan thread. Searching tells me it was last updated 1.49pm, so I should see it in the thread index on the group page between the Investor thread and the Multiple proposal thread

**Comment by gdpelican** [comment] 2016-07-12 15:45
This is actually a duplicate of #3368. Here's the process:

- We load the group
- (at the same time) we load the discussions in that group, and the subgroups in the group
- We create a view of discussions, which  
^^ If this step happens before the subgroups come back, it doesn't take those subgroups into account in the view, even though the discussions are loaded into the client side properly.

Working on a fix now.

**Closed by gdpelican** 2016-07-12 15:45 UTC
