### ISSUE TITLE
Oauth sign in doesn't "remember" you

### ISSUE THREAD

**Issue by jonlemmon** [loomio/loomio#1466] opened 2014-04-29 00:21 UTC
I've been signing in with Google, and every time I visit Loomio I have to re-login.

**Comment by denjello** [comment] 2015-01-29 16:12
No activity for a VERY long time. Close???

**Comment by robguthrie** [comment] 2015-02-01 19:54
It's still a bug, and one I'd really like to see fixed, but I don't know how to do it. Devise/Omniauth don't make this easy/clear.

**Comment by gdpelican** [comment] 2015-12-01 09:42
I'm going to close this as it's ancient and a duplicate of #2166

**Closed by gdpelican** 2015-12-01 09:42 UTC
Labels: Please help
