### ISSUE TITLE
sign in notification in wrong language

### ISSUE THREAD

**Issue by mixmix** [loomio/loomio#1862] opened 2015-02-01 22:59 UTC
sometimes when I log in I see a notification in a foreign language.
my saved language is English: 

http://i.imgur.com/xJY9Fkv.png
![](http://i.imgur.com/xJY9Fkv.png)

**Comment by gdpelican** [comment] 2015-02-01 23:00
+1 I noticed this as well.

**Comment by robguthrie** [comment] 2015-02-01 23:13
It's a pretty friendly kind of bug.

**Comment by denjello** [comment] 2015-02-05 12:08
@s01us > Is your browser set to Spanish? What route did you take to log in? Can you explain more carefully how to reproduce?

**Comment by robguthrie** [comment] 2015-02-06 02:06
This happens because when you're not signed in, we detect your locale from the browser info, and when you are signed in, locale (for those users who have saved it) is taken from the saved locale preference.

Specifically, 
```
flash[:notice] = t(:'devise.sessions.signed_in')
```
is being done before we do `set_application_locale`.

The difficulty is being able to `set_application_locale` after signing in the user, but before setting the flash message, because of the way the devise sessions controller works.

**Comment by gdpelican** [comment] 2015-02-06 02:08
I wonder if the 't' helper method can accept a locale as an argument in
some way?

**Comment by robguthrie** [comment] 2015-02-06 02:17
The problem is (as I understand it) .. I'm hesitant to reimplement sessions#create, so we're limited to before and after filters around sessions#create. I've always considered it a minor bug.. there is no real harm in seeing a welcome message in another language, and for me it wasnt worth taking on maintenance of possibly the most critical controller method of the app.

**Comment by s01us** [comment] 2015-02-06 12:44
i think you're right about the order of controller actions rob.

actually I think the easiest thing would be to disable that particular message - surely it's a bit redundant to tell people they're logged in ... they just came through the log in page ... and they've not been told they failed.

what do y'all reckon?

---

@denjello thanks for trying to help, I should have provided more context - I wrote a lot of the code around locales, and have discussed it with robguthrie before, so there was an assumption I knew about the browser settings. 
As a note I made a useful display to allow users to see their browser locale settings at the bottom of this page : www.loomio.org/translation (it's actually the union of browser reported and app-recognised, but it's a start)

**Comment by gdpelican** [comment] 2015-02-06 13:05
I have a mild suspicion this will fix it:
```
    sign_in(:user, user)
    flash[:notice] = t(:'devise.sessions.signed_in', locale: user_selected_locale)
```

Hell, I wouldn't be that surprised if just moving the flash setter after signing in might fix it:
```
    sign_in(:user, user)
    flash[:notice] = t(:'devise.sessions.signed_in')
```

But, as Rob said... it's a really minor bug. Happy to have someone pick it up, test it out, and get a PR in for it, but can't spare the time to spin it up right now.

**Comment by strypey** [comment] 2015-08-09 14:53
+1 to disabling the message. As @mixmix says it's surplus to requirement anyway, and although I agree it's an incredibly minor bug, I just think it's the sort of minor thing that could affect the first impressions of new users.

**Comment by gdpelican** [comment] 2016-01-05 05:12
Closing this as it's old, and constrained to the beta interface.

**Closed by gdpelican** 2016-01-05 05:12 UTC
Labels: Bug, Please help
