### ISSUE TITLE
Proposal padding

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3915] opened 2016-12-01 02:35 UTC
Seems like there was recently a deploy to adjust this:

I'm seeing this with a reload of loomio at 3:35pm on 1 december. (ie: just now)

![image](https://cloud.githubusercontent.com/assets/486367/20779828/cf4bc63e-b7db-11e6-8fa1-3a344c4ba454.png)

**Comment by mhjb** [comment] 2016-12-01 21:58
Duplicate of #3908

**Closed by mhjb** 2016-12-01 21:58 UTC
