### ISSUE TITLE
Firefox disallows selecting default time on datepicker

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4623] opened 2018-04-17 07:18 UTC
Step to reproduce:
on loomio.org, go to a discussion and create a time poll
in the modal, set a date and time slot, click on the + icon to add the option.
the + icon animates, but the time slot is not added to options
as it is impossible to create a time poll whitout time slots, this feature is not currently usable.

No console error are shown.

**Comment by gdpelican** [comment] 2018-04-17 07:39
I'm unable to reproduce this on loomio.org, but we did just deploy a
feature around this, so perhaps there's some browser caching problem going
on. Can you repro the issue once you've reloaded the app, and cleared your
browser cache (ctrl + reload)?

**Comment by juliencarnot** [comment] 2018-04-17 07:45
That's why I was testing it, to see the translation's context ;-)

I logged out and in and CTRL shift R on Firefox 59.0.2 and still reproduce it, but can't reproduce it on Chromium.

**Comment by gdpelican** [comment] 2018-04-18 07:08
It appears firefox has a bug around not allowing you to submit the default time, but works fine if you actually select a date from the picker.

It's high on our list to improve the datepicker for meeting polls, so I reckon we'll get to replacing this bit soon.

**Comment by gdpelican** [comment] 2018-05-16 04:42
@Space-Ed and I are now on our way to a much improved experience here, eta 2 weeks or so.

**Comment by robguthrie** [comment] 2019-10-10 20:09
fixed in loomio 2.0

**Closed by robguthrie** 2019-10-10 20:09 UTC
