### ISSUE TITLE
When I first propose and vote, the pie & my vote are not displayed

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#7415] opened 2021-03-14 19:43 UTC
Immediately after proposing and voting:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/1380991/111081897-58562400-856a-11eb-8660-45cd32d24ba8.png">

After refreshing:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1380991/111081915-6c9a2100-856a-11eb-8900-0779501b3192.png">

**Comment by chaotika** [comment] 2021-04-18 15:13
seems to be fixed in current master branch commit f33ed92e75de59910c1bda565edbda3bf2cf69ce

**Comment by robguthrie** [comment] 2021-04-18 19:34
no, i think this is still happening, it's kind of tricky to reproduce. I
will look again today

**Comment by robguthrie** [comment] 2021-04-28 23:35
I've fixed this bug now!

**Closed** 2023-08-20 04:09 UTC
