### ISSUE TITLE
Browser hangs when loading some threads

### ISSUE THREAD

**Issue by Miyou** [loomio/loomio#4510] opened 2018-01-31 12:37 UTC
I have a problem where the browser hangs and becomes unresponsive when trying to load certain threads. It only happens when logged into my account (although I tried making a second account and have the same problem there).
The threads load when adding a comment number to the url. For example `https://talk.theborderland.se/d/9EQT3dKL/fund-51-to-be-or-not-to-be-/` does not load, while `https://talk.theborderland.se/d/9EQT3dKL/fund-51-to-be-or-not-to-be-/149` does.
There is no difference in console output when loading the different urls.

What else can I do to help debug this?
Thanks!

**Comment by aerugo** [comment] 2018-01-31 13:07
I run the Borderland instance of Loomio, and I've had this report from another user too.
Browser hangs and uses 100% of CPU when loading that particular thread, but only when the user is logged in. If there is something I could look for in the logs, I have them at hand.

**Comment by gdpelican** [comment] 2018-01-31 13:25
A look at this has led me to believe that Faye (our trusty but ancient and unmaintained live-update service) may be choking alongside the new Rails 5 upgrade. I'm not certain why this seems to work with a comment ID in the url, but not upon loading the thread, but this explanation does jive with needing to be logged in to repro the error (logged out users do not get faye subscriptions)

@robguthrie and I were pawing today at moving over to ActionCable, which, if I'm right about this incompatibility, will become top priority. One thing that would help me to confirm is to see if removing FAYE_URL from your env (effectively turning off the live update server) seems to resolve the error. Would you be willing to give that a go?

**Comment by aerugo** [comment] 2018-01-31 13:30
Ok, good to hear that we’re onto something. If I were to do that,
everything would still work, except for live updates, correct?

**Comment by gdpelican** [comment] 2018-01-31 13:36
Yes, removing Faye won't break anything except for live updating.

**Comment by aerugo** [comment] 2018-01-31 14:24
Ok, I've commented out the FAYE_URL and live updates are now turned off.
@Miyou, can you replicate the error now?

**Comment by Miyou** [comment] 2018-01-31 14:30
Unfortunately still hangs :/

**Comment by aerugo** [comment] 2018-01-31 14:51
Ok, I'm re-enabling Faye.

**Comment by gdpelican** [comment] 2018-01-31 19:57
Hm, I can still replicate the error, but it seems there are still requests being made the the faye server. Did you `docker-compose down; docker-compose up -d` after changing the ENV?

![screen shot 2018-02-01 at 8 55 41 am](https://user-images.githubusercontent.com/750477/35644500-f411a018-072d-11e8-9842-a95d2306f0be.png)

**Comment by aerugo** [comment] 2018-01-31 20:05
I turned it back on when it didn't solve the issue for Miyou.
But Faye was definitely off when he tried it, I tested live updates and they were not on.
Turned it back off now, Docker is booting up again, you should be able to test in a minute or so.
Let me know when you're done so I can turn it back on, Loomio is really a bit crippled without it.

**Comment by gdpelican** [comment] 2018-01-31 20:09
Okay, thanks, I can confirm that's not the thing. I'll keep digging.

**Comment by gdpelican** [comment] 2018-01-31 22:45
Okay I have a fix for this in the pipeline. Thanks for your patience.

**Comment by gdpelican** [comment] 2018-01-31 23:01
Ref #4508 , fix #4511

**Comment by gdpelican** [comment] 2018-02-01 23:03
I've pushed this fix to loomio.org and into our stable branch; would you mind pulling and running the latest to see if this is fixed for you @aerugo ?

**Comment by aerugo** [comment] 2018-02-01 23:04
Will do! Just need to merge to my own branch first, but getting right on that.

**Comment by aerugo** [comment] 2018-02-01 23:38
I've deployed the fix to https://talk.theborderland.se, but since I was never able to replicate this error, @Miyou will have to check if the problem is solved.

**Comment by aerugo** [comment] 2018-02-01 23:46
YES! Another user who had the same problem reports that it's now fixed. We'll wait for @Miyou to check in, but YOU GUYS ROCK. I'm so god damn happy I picked Loomio for the Borderland.

**Comment by gdpelican** [comment] 2018-02-06 00:34
Thanks for the kind words; closing this now, please let me know of any other issues that may crop up in this direction.

**Closed by gdpelican** 2018-02-06 00:34 UTC

**Comment by Miyou** [comment] 2018-02-06 11:53
It indeed seems to be fixed for me now! Thanks and sorry for the delay!
