### ISSUE TITLE
Edit comment modal has gone miniature

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3642] opened 2016-08-18 22:47 UTC
The normal edit modal looks like this:
<img width="880" alt="screen shot 2016-08-19 at 10 46 04 am" src="https://cloud.githubusercontent.com/assets/5498878/17793297/4b0cb47e-65fa-11e6-9fe1-2a6fea943d5d.png">

But the edit comment one has recently become tiny like this:
<img width="769" alt="screen shot 2016-08-19 at 10 45 38 am" src="https://cloud.githubusercontent.com/assets/5498878/17793298/4ca40c56-65fa-11e6-9624-2c5d615d0cc3.png">

I'm on Mac using Firefox 48 if that matters.

**Comment by rdbartlett** [comment] 2016-08-22 03:32
thanks alanna, this is a dupe of #3634

**Closed by rdbartlett** 2016-08-22 03:32 UTC
