### ISSUE TITLE
Add subgroup form gives you the option to create Open subgroup even if parent is Secret

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#2888] opened 2016-01-20 23:08 UTC
...seems to revert to Closed afterwards but shouldn't show the option

**Comment by rdbartlett** [comment] 2016-02-08 22:40
dupe of #2899

**Comment by robguthrie** [comment] 2016-02-15 22:32
fixed, yay, closed

**Closed by robguthrie** 2016-02-15 22:32 UTC
