### ISSUE TITLE
Some API requirements

### ISSUE THREAD

**Issue by Floppy** [loomio/loomio#1530] opened 2014-06-10 10:40 UTC
We'd like to try out Loomio with the [OpenPolitics](http://github.com/openpolitics/manifesto) project. We currently discuss votes in pull requests, but Loomio might do a better job. So, in order to do this we would need API access to Loomio to do a few tasks. We currently have a [script that monitors vote status](http://github.com/openpolitics/votebot), so we'd be integrating into that. 

Note that I'm not massively familiar with Loomio yet, so apologies if some of this doesn't make sense.

First, we need to create a Loomio discussion automatically when a pull request is opened, and enter the link to the discussion as a PR comment. API features required:
* create discussion and set description (including links)
* get link to created discussion

Next, we'd need to monitor the status of the discussion and set github merge status appropriately. API features:
* get number of votes for/against/abstain for a discussion, and whether a vote has been passed.

Finally, when contributions are accepted, we'd need to invite the new contributors to Loomio and add them to later iscussions automatically. API features:
* create Loomio invitations for new users

Hopefully this helps show what we want to do... looking forward to having a go :)

**Comment by denjello** [comment] 2015-01-29 16:14
Is this an issue, or a discussion?

**Comment by Floppy** [comment] 2015-01-30 09:25
I originally added it as a discussion of a few of our API requirements, but I think the API has moved on a lot since then.

**Comment by lucideer** [comment] 2015-02-03 20:26
>  the API has moved on a lot

Querying a few of the current live endpoints anonymously give me 401s so I'm guessing the current v1 is intended user-centric access only? Has any thought been given to non-user-context API access discussed last summer?

Would be really nice if, for example, when visiting the following endpoint anonymously:
  `https://www.loomio.org/api/v1/discussions?group_id=3`
it returned a JSON serialisation of the content shown for logged out users visiting this page:
  `https://www.loomio.org/g/WmPCB3IR`

**Comment by robguthrie** [comment] 2015-02-03 21:52
we're still building on it. I completely agree with you on the intended behaviour @lucideer. 
IE:
If you are not logged in and request discussions index, then you should see public discussions

**Comment by denjello** [comment] 2015-02-03 21:59
+1 for transparency
+10 for federated data structures without middleware

**Comment by lucideer** [comment] 2015-08-13 18:31
> we're still building on it. I completely agree with you on the intended behaviour @lucideer.
> IE:
> If you are not logged in and request discussions index, then you should see public discussions

Has there been any movement on this? Just checked the same endpoints quickly now:

- https://www.loomio.org/api/v1/discussions?group_id=3 still works for authorised requests so I assume there hasn't been huge structural/functional changes
- https://www.loomio.org/api/v1/discussions?group_id=3 now returns a 500 instead of a 401 for anon requests

(and https://github.com/loomio/loomio/blob/master/config/routes.rb shows no v2 yet, so I assume I'm still looking at the endpoint for the current version)

**Comment by gdpelican** [comment] 2015-08-14 06:59
Hey @lucideer, there has been a bunch of movement on the API, but we've still been focusing primarily on internal usage at the moment (we've open sourced the client and server facing parts of the API, actually: www.github.com/gdpelican/snorlax; www.github.com/loomio/angular_record_store). 

Once Loomio 1.0 is released later in the year, we'll be be able to better prioritise public-facing content. We do have one endpoint exposed, a list of recent public motions which conform to the popolo spec (http://www.popoloproject.com/specs/motion.html), check it out here: 

```
https://www.loomio.org/api/popolo/motions.json
```
if there was an interested dev with a little experience out there I'd be more than happy to support her/him in getting some other endpoints exposed; it's really not a long ways off at all, but I can't guarantee it'll make it on our list before 1.0 is out in the wild. :tiger:

**Comment by lucideer** [comment] 2015-08-14 18:43
> if there was an interested dev with a little experience out there I'd be more than happy to support her/him in getting some other endpoints exposed

I'd love to, but I'm not a Ruby guy - I could probably figure it out without a lot of difficulty but I think maybe getting loomio running in a deb env to begin with might be my biggest hurdle

**Comment by gdpelican** [comment] 2015-08-14 19:04
Have you had a peek through the dev environment startup instructions? 
https://github.com/loomio/loomio/wiki/Setup-a-Loomio-development-environment

Those are instructions for Ubuntu, but I can't imagine differences for Debian would be too severe (and we'd be happy to hear about them in a PR to that doc!)

You won't even need to worry about setting up the angular frontend business if you're just intending to work on the API, and if you get stuck, let me know. If you don't get stuck, let me know that, and I'll send over some instructions for how to get those endpoints working for you. :ok:!

**Comment by gdpelican** [comment] 2015-12-01 09:41
Going to close this as it's not a particular 'issue' for us to fix at this point. If anyone's interested in using the Loomio API, get in touch with me and we'll discuss further how to make that easy for you.

**Closed by gdpelican** 2015-12-01 09:41 UTC
