### ISSUE TITLE
Pasting image from clipboard as attachment is broken

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3613] opened 2016-08-11 02:13 UTC
When I use Command, Control, Shift, 4 to select an area and copy it to clipboard, then command + v to paste it into a loomio attachment, something does not go correctly.

It brings up a progress bar, but then fails to show an attachment has been added. I wonder if it is as simple as needing some kind of filename.

Uploading progress
![image](https://cloud.githubusercontent.com/assets/486367/17577068/c48dc44c-5fcd-11e6-938b-0657fdfce7b7.png)

Final result
![image](https://cloud.githubusercontent.com/assets/486367/17577073/d406c112-5fcd-11e6-8eeb-da7725483dec.png)

**Comment by robguthrie** [comment] 2016-08-11 02:14
Chrome and Mac

**Comment by gdpelican** [comment] 2016-08-11 04:50
Thanks; this is a dupe of #3439

**Closed by gdpelican** 2016-08-11 04:50 UTC
