### ISSUE TITLE
Login issue with KeeFox

### ISSUE THREAD

**Issue by ntnsndr** [loomio/loomio#3766] opened 2016-10-07 15:19 UTC
Friends,

Just a small issue, but I thought I'd mention it. I use the password manager KeePass, aided by the Firefox plugin Keefox. It automatically enters my login credentials when I try to sign in to Loomio, but when it does that, and I submit, I'm told that the credentials are incorrect. It works, however, when I remove and retype one character in each field. I suspect this is some kind of security precaution to prevent spam logins. But in this case it prevents a legitimate login.

At the very least, perhaps, the system could be adjusted to correctly explain the reason for the login failure: rather than the credentials being incorrect, make clear that it didn't work because the credentials weren't manually entered.

Even better, is there a way to withdraw that security precaution, or adjust it? On some sites, it's sufficient to simply manually click in both fields, rather than having to type a character. Since I don't actually know my passwords (they're all random strings), it's quite an inconvenience to have to look the password up to re-enter. Ideally, no additional manual action should be required other than clicking "submit" (or whatever the button says).

Improving this interaction would be a nice way of helping to support those of us who are trying to use strenuous security practices.

Thanks for all your extraordinary work! I'm really enjoying the experience of organizing #BuyTwitter with Loomio.

**Comment by gdpelican** [comment] 2016-10-07 15:28
Hi @ntnsndr , thanks for the detailed report and kind words.

Could you clarify whether you're experiencing this on the sign in page (IE, by visiting `loomio.org/users/sign_in`), or via the in-app sign in (IE, by visiting `loomio.org/dashboard` directly while logged out)? Or both?

**Comment by ntnsndr** [comment] 2016-10-07 15:31
Thanks for the clarifying question! Just the in-app sign-in. The main sign-in page works fine.

**Comment by Erudition** [comment] 2017-03-29 21:53
Also using KeeFox - confirmed.

**Comment by robguthrie** [comment] 2017-11-01 22:09
we've since rewritten our login system. closing

**Closed by robguthrie** 2017-11-01 22:09 UTC
Labels: Bug, Needs Confirmation, Priority: Trivial
