### ISSUE TITLE
attaching file to comment shows 2 attachement icons

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4433] opened 2017-11-26 20:35 UTC
Attaching a file to a comment shows it twice, and it appears twice in the activity card, deleting one of them deletes both. @gdpelican fyi.

**Comment by mhjb** [comment] 2017-11-27 06:21
looks like a duplicate of #4425

**Comment by BenDawes** [comment] 2017-11-28 22:50
https://github.com/loomio/loomio/pull/4438

**Comment by mhjb** [comment] 2017-12-07 22:59
I think this is fixed now.

**Closed by mhjb** 2017-12-07 22:59 UTC
