### ISSUE TITLE
attachments can't be deleted or changed when editing thread context

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3892] opened 2016-11-21 23:24 UTC
it seems like a bug, I didn't manage to change it on a test group. Rob said he could see the attachment and could delete after refreshing the page.

**Comment by HSalmon** [comment] 2016-12-09 01:04
I can't reproduce this. @natiloomio, have you had further trouble?

**Comment by natiloomio** [comment] 2016-12-15 01:13
I haven't heard about it again

**Comment by HSalmon** [comment] 2016-12-19 02:10
Closing for now, can reopen if we get further reports

**Closed by HSalmon** 2016-12-19 02:10 UTC
Labels: Bug, Needs Confirmation
