### ISSUE TITLE
Thread volume wrong

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3624] opened 2016-08-12 04:33 UTC
Michael just showed me some buggy behaviour. His volume setting for the Workers subgroup is 'Important activity', and it's been that way for ages. However some threads in that group are set for him to 'all activity', though he hasn't changed their setting. I've started exploring this here https://metabase.loomio.io/card/192 but haven't figured out what's going on.

**Comment by HSalmon** [comment] 2016-08-14 09:00
This may be a hangover from when we updated the default group volume from 'All activity' to 'Important activity'

**Comment by HSalmon** [comment] 2016-08-15 02:42
@mhjb, can you confirm that these are threads Michael has participated in (and to what capacity), or started?

**Comment by mhjb** [comment] 2016-08-15 02:50
It happened at least sometimes with threads he didn't start. I don't know re. participating. I've just added it to the above linked metabase card. Maybe we can quiz Michael again soon to spot another instance & then investigate it

**Comment by rdbartlett** [comment] 2016-08-16 23:37
Just checked in with Michael about this. It's not a bug, he just didn't understand that there are 3 different places to configure emails: thread, group, and global. He had 'subscribe on participation' checked. 

To me this is an argument to add a link from the thread- and group-email settings modal to the global email settings page.

Not a priority for me now though.

**Closed by rdbartlett** 2016-08-16 23:37 UTC
Labels: Needs Confirmation, Weird
