### ISSUE TITLE
Seems impossible to create an account after Google reject

### ISSUE THREAD

**Issue by a-pirard** [loomio/loomio#2028] opened 2015-03-23 17:01 UTC
I am [trying to] paste my message on request of Dan.
E-mail me if you want a better copy of the "welcome dialog" page by e-mail

-------- Original Message --------
Subject: 	Re: [Tagging] Loomio evaluation
Date: 	Mon, 23 Mar 2015 16:46:00 +0000
From: 	Dan S <danstowell+osm@gmail.com>
Reply-To: 	Tag discussion, strategy and related tools <tagging@openstreetmap.org>
To: 	Tag discussion, strategy and related tools <tagging@openstreetmap.org>

I don't know if I need to say this, but Ralph, Andre, please could you
send report your problems to the loomio people? You do that here:
https://github.com/loomio/loomio/issues

Dan

-------- Original Message --------
Subject: 	Re: [Tagging] Loomio evaluation
Date: 	Mon, 23 Mar 2015 10:36:08 +0100
From: 	André Pirard <A.Pirard.Papou@gmail.com>
Reply-To: 	Tag discussion, strategy and related tools <tagging@openstreetmap.org>
To: 	kotya.lists@gmail.com, "Tag discussion, strategy and related tools" <tagging@openstreetmap.org>
On Mon, Mar 23, 2015 at 5:57 AM, Dan S <danstowell+osm@gmail.com> wrote:
> It's interesting. I hadn't realised it's open-source too, so osm could
> run its own version of it if we wanted to.
>
> Dan
>
> 2015-03-20 22:38 GMT+00:00 Kotya Karapetyan <kotya.lists@gmail.com>:
> > Dear all,
> >
> > In an attempt to find a better tool for our proposal discussions, Loomio has
> > been mentioned. At the very first glance it looks like a feasible
> > alternative to the mailing list and the forum.
> >
> > Let's take a look together: https://www.loomio.org/g/tknueHrw/osm-tagging
> >
> > And let me know if you want to check the coordinator role.
> >
> > Cheers,
> > Kotya
Hi,

I clicked "Login via Google", Google didn't let me choose which e-mail address to use, it blindly used the wrong one, I obviously canceled permission to use it and Loomio reported failure for a cryptic reason.
Back to Loomio for a new start, I'm stuck in the following welcome dialog when trying to repeat the same.
It looks like Loomio made a subscription despite it failed and wants me to do an impossible login.
According to Help, no subscription is needed
How can I cancel that bogus subscription and go on? (I have an idea of trickery, but I prefer the official method).

Short conclusion: it seems I won the contest by raising a bug on just a single first click ;-)

> Link up your account
>
> Log in to your Loomio account to link it up with Google.
> or
> Remember me
> Forgot your password?
>
> Don't have an account? Create one now
Cheers
André.

**Comment by gdpelican** [comment] 2015-03-23 23:28
Thanks @a-pirard; I'm going to take a peek at this this morning to see if there's a quick fix.

**Comment by gdpelican** [comment] 2015-03-24 00:24
Hm, after playing with this for a few minutes, I'm not able to reproduce your issue. If you have some more specific repro steps (what does 'Back to Loomio for a new start' mean specifically? Screenshots appreciated!), feel free to post em here or shoot em towards james at loomio dot org.

Thanks!
:palm_tree:

**Comment by a-pirard** [comment] 2015-03-24 03:08
On 2015-03-24 01:24, James Kiesel wrote
      :
    
    
      Hm, after playing with this for a few minutes, I'm not able to
        reproduce your issue. If you have some more specific repro steps
        (what does 'Back to Loomio for a new start' mean specifically?
        Screenshots appreciated!), feel free to post em here or shoot em
        towards james at loomio dot org.
      Thanks!
    
    
    Hi,
    
    First, did you get that "a-pirard" from your system or did you make
    it up?  That might be a clue.
    I don't see why make screenshots (big images) when copy&paste
    should reproduce the screen and does it fairly well.
    
    'Back to Loomio for a new start' means that I go back to
    https://www.loomio.org/g/tknueHrw/osm-tagging as requested.
    Or anything at https://www.loomio.org/ 
    and, obviously, click on   Log in  as the
    first time.
    
    
    Link up your account
    Log in to your Loomio account to link it up with Google.
    
      
        
          or
        
      
      
        
          
            
          
        
        
          
            
            
              
                
                  
                    Log in
                    
                    
                  
                
              
            
            
          
        
        
          
            
              
                Remember me
              
          
          
            Forgot
              your password?
          
        
        
          
            
              Don't have an account?
              Create one
                now
            
          
        
      
    
    
    The first time I clicked login, I was sent
    to Google and Google did not let me choose an address and used the
    wrong one.
    And now, oops, if I click Log in Loomio is insisting on using the
    wrong address...
    
    
    
      
        
          
            
              
                
                  
                    Confirm your details
                    Now that you've logged in with Google, please
                      confirm your details to create a Loomio account.
                    
                      Already have a Loomio account?
                      Link
                        it up instead
                    
                    
                      
                        
                          
                            
                            
                              
                                
                                  
                                    Create account
                                    
                                    
                                  
                                
                              
                            
                            
                          
                        
                        
                          
                        
                      
                    
                    By clicking Create account, you
                      agree to Loomio's Terms of service
                  
                
              
            
          
        
      
    
    
    
    I have disconnected all my Google accounts, no help.
    I never clicked "remember me", no way.
    
    Loomio does not let me use the Google account I want.
    
    
    Cheers
    
    
    
      
        
          André.

**Comment by a-pirard** [comment] 2015-03-24 03:29
Testing the left pane of the Tour Eiffel.
    Way: Eiffel Tower (5013364)
    
    
       Fix wikipedia links
      
       Edited 3 months ago by Med
      
       Version #85 · Changeset #27446980
      
      Tags
      
        
          
            architect
            Stephen Sauvestre;Gustave
              Eiffel;Maurice Koechlin;Émile Nouguier
          
          
            building
            yes
          
          
            building:colour
            #706550
          
          
            building:material
            iron
          
          
            building:min_height
            4
          
          
            building:part
            no
          
          
            building:shape
            pyramidal
          
          
            height
            324 m
          
          
            image
            http://upload.wikimedia.org/wikipedia/commons/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg
          
          
            importance
            international
          
          
            layer
            2
          
          
            man_made
            tower
          
          
            name
            Tour Eiffel
          
          
            name:af
            Eiffel-toring
          
          
            name:ast
            Torrne Eiffel
          
          
            name:ba
            Эйфель башняһы
          
          
            name:cs
            Eiffelova věž
          
          
            name:da
            Eiffeltårnet
          
          
            name:de
            Eiffelturm
          
          
            name:en
            Eiffel Tower
          
          
            name:es
            Torre Eiffel
          
          
            name:et
            Eiffeli torn
          
          
            name:fa
            برج ایفل
          
          
            name:fi
            Eiffel-torni
          
          
            name:hr
            Eiffelov toranj
          
          
            name:hu
            Eiffel-torony
          
          
            name:id
            Menara Eiffel
          
          
            name:it
            Torre Eiffel
          
          
            name:ja
            エッフェル塔
          
          
            name:ko
            에펠탑
          
          
            name:ku
            Barûya Eyfelê
          
          
            name:la
            Turris Eiffelia
          
          
            name:lb
            Eiffeltuerm
          
          
            name:nl
            Eiffeltoren
          
          
            name:ru
            Эйфелева башня
          
          
            name:sk
            Eiffelova veža
          
          
            name:sv
            Eiffeltornet
          
          
            name:tr
            Eyfel Kulesi
          
          
            name:tt
            Эйфель манарасы
          
          
            name:uk
            Ейфелева вежа
          
          
            name:vi
            Tháp Eiffel
          
          
            name:zh
            埃菲尔铁塔
          
          
            source:building
            http://fr.wikipedia.org/wiki/Donn%C3%A9es_techniques_de_la_tour_Eiffel
          
          
            tourism
            attraction
          
          
            tourism:visitors
            7000000
          
          
            wheelchair
            yes
          
          
            wikipedia
            fr:Tour
                Eiffel
          
          
            wikipedia:de
            Eiffelturm
          
        
      
      Nodes
      
         33388356
          (part of way South
              Pillar (69034179)) 
         639613234
          (part of ways 69034130
          and South
              Pillar (69034179)) 
         639613207
          (part of way South
              Pillar (69034179)) 
         33388327
          (part of way South
              Pillar (69034179)) 
         639613243
          (part of way South
              Pillar (69034179)) 
         33388329
          (part of way South
              Pillar (69034179)) 
         828533301
          (part of ways 50473353
          and South
              Pillar (69034179)) 
         3139588819
          (part of ways 50473353,
          South
              Pillar (69034179), 308077768,
          and 308689165)
        
         3139564403
          (part of ways 308077768
          and 308689165)
        
         3139564405
          (part of ways 308077768
          and 308689165)
        
         3139624571
          (part of ways 308077773,
          308077768,
          308689165,
          and 308695359)
        
         33388330
          (part of ways 308077768
          and 308689165)
        
         3139564410
          (part of ways 308077768
          and 308689165)
        
         33388332
          (part of ways 308077768
          and 308689165)
        
         3139564415
          (part of ways 308077768
          and 308689165)
        
         3139564417
          (part of ways 308077768
          and 308689165)
        
         335600369
          (part of ways 308077768
          and 308689165)
        
         3139564421
          (part of ways 308077768
          and 308689165)
        
         33388333
          (part of ways 308077770,
          308077768,
          308689165,
          and 308695357)
        
         3139564425
          (part of ways 308077768
          and 308689165)
        
         3139564426
          (part of ways 308077768
          and 308689165)
        
         33388334
          (part of ways 50473353,
          East
              Pillar (69034180), 308077768,
          and 308689165)
        
         828532883
          (part of ways 50473353
          and East
              Pillar (69034180)) 
         33388335
          (part of way East
              Pillar (69034180)) 
         639613322
          (part of way East
              Pillar (69034180)) 
         33388336
          (part of way East
              Pillar (69034180)) 
         639613336
          (part of way East
              Pillar (69034180)) 
         33388337
          (part of way East
              Pillar (69034180)) 
         828530646
          (part of way East
              Pillar (69034180)) 
         3139781279
          (part of way 308689166)
        
         3139781276
          (part of way 308689166)
        
         3139564531
          (part of way 308689166)
        
         33388338
          (part of way 308689166)
        
         3139564534
          (part of way 308689166)
        
         33388339
          (part of way 308689166)
        
         335600372
          (part of way 308689166)
        
         3139564541
          (part of way 308689166)
        
         33388340
          (part of way 308689166)
        
         641972287
          (part of way 308689166)
        
         3139564546
          (part of way 308689166)
        
         335600368
          (part of way 308689166)
        
         3139564549
          (part of way 308689166)
        
         3139564551
          (part of way 308689166)
        
         3139781284
          (part of way 308689166)
        
         828532672
          (part of way North
              Pillar (69034127)) 
         33388342
        
         639613303
          (part of way North
              Pillar (69034127)) 
         33388343
          (part of way North
              Pillar (69034127)) 
         639613276
          (part of way North
              Pillar (69034127)) 
         33388344
        
         33388345
          (part of ways 50473353,
          308077768,
          and 308689167)
        
         3139564552
          (part of ways 308077768
          and 308689167)
        
         3139564550
          (part of ways 308077768
          and 308689167)
        
         3139624572
          (part of ways 308695356,
          34180826,
          308077768,
          and 308689167)
        
         3139564547
          (part of ways 308077768
          and 308689167)
        
         3139564545
          (part of ways 308077768
          and 308689167)
        
         33388346
          (part of ways 308077768
          and 308689167)
        
         3139564540
          (part of ways 308077768
          and 308689167)
        
         3139564538
          (part of ways 308077768
          and 308689167)
        
         3139564536
          (part of ways 308077768
          and 308689167)
        
         3139564535
          (part of ways 308077768
          and 308689167)
        
         335600371
          (part of ways 51259179,
          308695358,
          308077768,
          and 308689167)
        
         33388347
          (part of ways 308077768
          and 308689167)
        
         33388348
          (part of ways 308077768
          and 308689167)
        
         639613263
          (part of ways 50473353,
          West
              Pillar (69034135), 308077768,
          and 308689167)
        
         33388349
        
         639613264
          (part of way West
              Pillar (69034135)) 
         33388350
          (part of way West
              Pillar (69034135)) 
         639613214
          (part of way West
              Pillar (69034135)) 
         33388351
          (part of way West
              Pillar (69034135)) 
         828532987
          (part of way West
              Pillar (69034135)) 
         33388352
          (part of way 308689164)
        
         33388353
          (part of way 308689164)
        
         3139781254
          (part of way 308689164)
        
         3139781253
          (part of way 308689164)
        
         3139564423
          (part of way 308689164)
        
         3139564420
          (part of way 308689164)
        
         335600370
          (part of way 308689164)
        
         3139564416
          (part of way 308689164)
        
         3139564414
          (part of way 308689164)
        
         3139564412
          (part of way 308689164)
        
         33388354
          (part of way 308689164)
        
         3139564409
          (part of way 308689164)
        
         3139564407
          (part of way 308689164)
        
         641972277
          (part of way 308689164)
        
         3139564404
          (part of way 308689164)
        
         3139564402
          (part of way 308689164)
        
         3139781237
          (part of way 308689164)
        
         33388355
          (part of way 308689164)
        
         828532221
          (part of way South
              Pillar (69034179)) 
         828530849
          (part of way South
              Pillar (69034179)) 
         33388356
          (part of way South
              Pillar (69034179)) 
      
      Part of
      
        Relation 4114843
          (as outline)

**Comment by a-pirard** [comment] 2015-03-24 03:34
Well, according to the previous message, this is a Web page that cannot display HTML ;-)

**Comment by a-pirard** [comment] 2015-03-25 21:37
On 2015-03-24 01:24, James Kiesel wrote :
>
> Hm, after playing with this for a few minutes, I'm not able to
> reproduce your issue. If you have some more specific repro steps (what
> does 'Back to Loomio for a new start' mean specifically? Screenshots
> appreciated!), feel free to post em here or shoot em towards james at
> loomio dot org.
>
> Thanks!
>

Hi,

First, did you get that "a-pirard" from your system or did you make it
up?  That might be a clue.
I don't see why make screenshots (big images) when copy&paste should
reproduce the screen and does it fairly well.

'Back to Loomio for a new start' means that I go back to
https://www.loomio.org/g/tknueHrw/osm-tagging as requested.
Or anything at https://www.loomio.org/
and, obviously, click on   Log in
<https://www.loomio.org/users/sign_in>  as the first time.

------------------------------------------------------------------------


  Link up your account

Log in to your Loomio account to link it up with Google.

or





Log in


Remember me
Forgot your password? <https://www.loomio.org/users/password/new>

Don't have an account? Create one now
<https://www.loomio.org/users/sign_up>


------------------------------------------------------------------------
The first time I clicked login, I was sent to Google and Google did not
let me choose an address and used the wrong one.
And now, oops, if I click Log in Loomio is insisting on using the wrong
address...

------------------------------------------------------------------------


  Confirm your details

Now that you've logged in with Google, please confirm your details to
create a Loomio account.

*Already have a Loomio account?* Link it up instead
<https://www.loomio.org/users/sign_in>




Create account


By clicking Create account, you agree to Loomio's Terms of service
<https://www.loomio.org/terms_of_service>


------------------------------------------------------------------------

I have disconnected all my Google accounts, no help.
I never clicked "remember me", no way.

Loomio does not let me use the Google account I want.

------------------------------------------------------------------------

Cheers

André.

**Comment by gdpelican** [comment] 2015-11-29 23:24
This is ancient, and still not sure exactly what the issue is here, so closing. Feel free to open a new one if you're still experiencing this :rabbit:

**Closed by gdpelican** 2015-11-29 23:24 UTC
